# wrangler.toml — PowerDialer (Pages + Functions)

name                 = "powerdialer-worker"   # worker name (ignored by Pages, but fine to keep)
compatibility_date   = "2025-07-15"
compatibility_flags  = ["nodejs_compat"]      # polyfill Node core modules for Twilio SDK
pages_build_output_dir = "./dist"             # Vite build output

[vars]                                     # runtime env vars for your Functions
AIRTABLE_BASE  = "apprTpOIFRuckIZJz"
AIRTABLE_TABLE = "Interaction / Activities"
# AIRTABLE_TOKEN stays a secret; don’t hard-code it here
