name = "powerdialer"
compatibility_date = "2025-01-15"
pages_build_output_dir = "./dist"
compatibility_flags = ["nodejs_compat"]

# Your existing KV namespace
[[kv_namespaces]]
binding = "OUTCOMES_KV"
id = "7bbc9e3c31d04d87893e4ceb06f75d43"
preview_id = "4712224be26b4380aa69ae146fb8d351"