# wrangler.toml

name = "powerdialer"
compatibility_date = "2025-07-15"
pages_build_output_dir = "./dist"

[functions]
external = ["jose"]

[env.production]
name = "powerdialer"
compatibility_date = "2025-07-15"

# ⬇️ Secrets already added via dashboard
# npx wrangler secret put commands commented out since managed in UI
# [observability.logs]  # Commented out—Pages doesn't support; enable via Worker dashboard
# enabled = true